### ISSUE TITLE
SendToAddress glitch

### ISSUE THREAD

**Issue by zhiyan114** [cryptean/bitcoinlib#65]
Hi so everytime when i run the sendtoaddress in C#, and enabledsubtractfeefromamount, it keeps subtracting the fees from the balance instead of the amount of coin they sent, can this be fixed?

**Comment by moodmosaic** [comment]
Thank you for reporting this. Which version of Bitcoin Core are you running?

**Comment by zhiyan114** [comment]
1.16.X bitcoin cash (using testnet to test the lib out)

**Comment by moodmosaic** [comment]
Can you get the latest from `master` and try again? If that solves your problem, it'll be available on NuGet in the next release.

**Comment by moodmosaic** [comment]
Is this still an issue?

**Comment by stjordanis** [comment]
this is fixed via
 https://github.com/cryptean/bitcoinlib/pull/70/commits/94c6ea767beccffcad5c8121b8316d7ec8cb48c8
