### ISSUE TITLE
Add estimatesmartfee call

### ISSUE THREAD

**Issue by bazooka70** [cryptean/bitcoinlib#71]
Is it possible to add the `estimatesmartfee ` RPC call please?

**Comment by moodmosaic** [comment]
Yes, that's a nice one to have, as it estimates the transaction fee per kilobyte that needs to be paid for a transaction to be included within a certain number of blocks.

**Comment by bazooka70** [comment]
Also note that `estimatefee `and `estimaterawfee ` are long DEPRECATED in 0.15+

**Comment by bazooka70** [comment]
This is the workaround I use so far:

```
public class GetEstimateSmartFeeResponse
{
    public decimal feerate;
    public ushort blocks;
}

IBitcoinService bitcoinService = new BitcoinService(useTestnet: false);
BitcoinLib.RPC.Connector.IRpcConnector _rpcConnector = new BitcoinLib.RPC.Connector.RpcConnector(bitcoinService);
var response = new GetEstimateSmartFeeResponse();                                   
response = _rpcConnector.MakeRequest<GetEstimateSmartFeeResponse>(BitcoinLib.RPC.Specifications.RpcMethods.estimatesmartfee, 6);
```

Not sure if this code perfect but it works for me.

**Comment by moodmosaic** [comment]
Resolved by https://github.com/cryptean/bitcoinlib/pull/75.
