### ISSUE TITLE
Always return 0 balance

### ISSUE THREAD

**Issue by proBeejay141** [cryptean/bitcoinlib#72]
i try to use bitcoinLib with rpc.blockchain.info , it's always return 0 as balance

**Comment by moodmosaic** [comment]
Can you point us to the exact URL of the REST API?

**Comment by proBeejay141** [comment]
rpc.blockchain.info, is an rpc endpoint from blockchain.info, i can't afford downloading the full block to my system, so i need to use an rpc to a public node

**Comment by moodmosaic** [comment]
I only see https://blockchain.info/api. From there, where should I go in order to see the API docs for it?

**Comment by proBeejay141** [comment]
https://blockchain.info/es/api/json_rpc_api

**Comment by proBeejay141** [comment]
have you look it up?

**Comment by moodmosaic** [comment]
Closing this as non-reproducible. Feel free to reopen it, add comments to it, but most importantly, provide some examples to it.
