### ISSUE TITLE
GetAccount method returns empty string

### ISSUE THREAD

**Issue by Givko** [cryptean/bitcoinlib#86]
When I call the `GetAccount` method with a valid Bitcoin address on the testnet the method returns an empty string. This happens for every address I pass to the method. I need the account to send bitcoins via the `SendFrom` method which first parameter is `FromAccount`

```
public string SendFrom(
    string fromAccount, string toBitcoinAddress, decimal amount, int minConf, string comment, string commentTo)
```

I know the address is valid because I have transfered bitcoins to it. 

If this is not the way to send bitcoins from one address to another could you please tell me which is the correct way to send coins from one address to another. Because I need to send coins from multiple addresses.

**Comment by moodmosaic** [comment]
All JSON-RPC account calls are/have been deprecated, [and will be removed entirely in v0.18](https://github.com/bitcoin/bitcoin/commit/3576ab126121f9bfb4d4d6195cbbe7ba30619f77). Right now, what you can do is to start `bitcoind` with the `-deprecatedrpc=accounts` switch.

**Comment by moodmosaic** [comment]
Closing this, given the resolution above. Feel free to reopen it, or add comments to it.
