### ISSUE TITLE
ListSinceBlock passing wrong parameter by default

### ISSUE THREAD

**Issue by LookBehind** [cryptean/bitcoinlib#88]
`public ListSinceBlockResponse ListSinceBlock(string blockHash, int targetConfirmations, bool? includeWatchonly)
        {
            return includeWatchonly == null
                ? _rpcConnector.MakeRequest<ListSinceBlockResponse>(RpcMethods.listsinceblock, (string.IsNullOrWhiteSpace(blockHash) ? "*" : blockHash), targetConfirmations)
                : _rpcConnector.MakeRequest<ListSinceBlockResponse>(RpcMethods.listsinceblock, (string.IsNullOrWhiteSpace(blockHash) ? "*" : blockHash), targetConfirmations, includeWatchonly);
        }`

When blockHash parameter is omitted - function should not fail, but instead should return all transactions. Right now it passes "*" when nothing specified, which is wrong. The fix is to supply empty string in that case.
Results: 
Before fix - Invoking method with blockHash as empty string results in exception from bitcoin rpc service.
After fix - Returns all transactions since genesis block.

**Comment by moodmosaic** [comment]
Cool :+1:  We'll take a look in order to (hopefully) make a potential fix available in the next release.

**Comment by moodmosaic** [comment]
Resolved in #89. It should be available in the next release on NuGet later on this week.

**Comment by moodmosaic** [comment]
Now live in https://www.nuget.org/packages/BitcoinLib/1.10.0 :rocket:
