### ISSUE TITLE
How to create transactions that carry messages in OP_RETURN

### ISSUE THREAD

**Issue by wcc19840827** [cryptean/bitcoinlib#91]
How to create transactions that carry messages in OP_RETURN

**Comment by moodmosaic** [comment]
Thank you for asking. I've been busy and I expect to get back to this over the next couple of days.

**Comment by moodmosaic** [comment]
You'd have to follow [these steps](https://bitcoin.stackexchange.com/a/32053) (limit is [40 bytes](https://github.com/bitcoin/bitcoin/pull/3737)) and you can check if the metadata is broadcasted [here](http://testnet.coinsecrets.org/).

---

FWIW, an important aspect of OP_RETURN is that outputs which use it in the standard way are provable unspendable.
