### ISSUE TITLE
Getblocktemplate does not provide txid, only hash

### ISSUE THREAD

**Issue by Behzod85** [cryptean/bitcoinlib#92]
Is it OK to calculate merkle root with hash? What about witness transactions?

**Comment by moodmosaic** [comment]
Thank you for asking. I've been busy and I expect to get back to this over the next couple of days.

**Comment by moodmosaic** [comment]
That's a 'bug', in the sense that `TxId` isn't included in [GetBlockTemplateTransaction](https://github.com/cryptean/bitcoinlib/blob/a2905e4cf26de3cab0923fa9cffa0d195f858384/src/BitcoinLib/Responses/GetBlockTemplateResponse.cs#L34) (only `Hash` does). Feel free to send us a pull request that adds it as a property—chances are it'll work:

```diff
 public class GetBlockTemplateTransaction
 {
     public string Data { get; set; }
     public string Hash { get; set; }
+    public string TxId { get; set; }
     public List<string> Depends { get; set; }
     public int Fee { get; set; }
     public int Sigops { get; set; }
 }
```

**Comment by moodmosaic** [comment]
You'll need `TxId` to calculate the witness root hash, as per the [BIP: 141](https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki#commitment-structure).
