### ISSUE TITLE
No support for new label system

### ISSUE THREAD

**Issue by Sword-Smith** [cryptean/bitcoinlib#93]
Cf. https://github.com/bitcoin-dot-org/bitcoin.org/issues/1287, the account system has been deprecated and will be removed in Bitcoin Core 0.18. But I cannot see that this repo uses the new label system. The deprecated and new methods are listed here:
https://bitcoincore.org/en/releases/0.17.0/#label-and-account-apis-for-wallet

**Comment by Sword-Smith** [comment]
I plan on making a pull request so the author does not have to respond to this issue.

**Comment by moodmosaic** [comment]
@Sword-Smith, please do. I'll make sure your pull request gets reviewed (and merged) the soonest possible.

**Comment by moodmosaic** [comment]
Resolved by #94. Released on NuGet as [BitcoinLib 1.11.0](https://www.nuget.org/packages/BitcoinLib/1.11.0).
